spring:
  redis:
    host: localhost
    database: 1
    port: 6379
    password:

  # 多数据源配置
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/how2java?serverTimezone=Asia/Shanghai
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://localhost:3306/how2java?serverTimezone=Asia/Shanghai
      username: malf
      password: malinfei921020
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://localhost:3306/how2java?serverTimezone=Asia/Shanghai
      username: lingfeng23
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis 配置(同 MybatisConfig 文件配置)
#mybatis:
#  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应 mapper 映射 xml 文件的所在路径
#  type-aliases-package: com.malf.entity  #注意：对应实体类的路径
server:
  port: 9090
